// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortfolioApp.Data;

#nullable disable

namespace PortfolioApp.Data.Migrations
{
    [DbContext(typeof(PortfolioDbContext))]
    [Migration("20260713095659_AddUnitModelFileName")]
    partial class AddUnitModelFileName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("PortfolioApp.Models.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AveragePowerUsage")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelFileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WarrantyYears")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WidthPerZone")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Zones")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("PortfolioApp.Models.Watermark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Grayscale")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("StoredFileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Watermarks");
                });

            modelBuilder.Entity("PortfolioApp.Models.Unit", b =>
                {
                    b.OwnsOne("BlazorThreeJS.Maths.Vector3", "Rotation", b1 =>
                        {
                            b1.Property<int>("UnitId")
                                .HasColumnType("INTEGER");

                            b1.Property<double>("X")
                                .HasColumnType("REAL");

                            b1.Property<double>("Y")
                                .HasColumnType("REAL");

                            b1.Property<double>("Z")
                                .HasColumnType("REAL");

                            b1.HasKey("UnitId");

                            b1.ToTable("Units");

                            b1.WithOwner()
                                .HasForeignKey("UnitId");
                        });

                    b.Navigation("Rotation")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
